// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv2cBPbx8Q0G9f2WKIBEw8Os_rw-i1OWA',
    appId: '1:315916933145:web:022dc93fccc743b4bd7288',
    messagingSenderId: '315916933145',
    projectId: 'untitled-d45f0',
    authDomain: 'untitled-d45f0.firebaseapp.com',
    storageBucket: 'untitled-d45f0.appspot.com',
    measurementId: 'G-4X1L7QD6LH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY1UXGkEcVm6oYRf6NaHQrVowBaW9-3Eg',
    appId: '1:315916933145:android:5cf0dec84ac84f0ebd7288',
    messagingSenderId: '315916933145',
    projectId: 'untitled-d45f0',
    storageBucket: 'untitled-d45f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBWx7wvn2tz8NwFUnaoMXlO6VWQD9aMRc',
    appId: '1:315916933145:ios:b5841ec9476a2528bd7288',
    messagingSenderId: '315916933145',
    projectId: 'untitled-d45f0',
    storageBucket: 'untitled-d45f0.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv2cBPbx8Q0G9f2WKIBEw8Os_rw-i1OWA',
    appId: '1:315916933145:web:b15ca0c808eb0756bd7288',
    messagingSenderId: '315916933145',
    projectId: 'untitled-d45f0',
    authDomain: 'untitled-d45f0.firebaseapp.com',
    storageBucket: 'untitled-d45f0.appspot.com',
    measurementId: 'G-60KH6GCS1X',
  );
}